name: Lint
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lua:
    name: Lua
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: sudo apt-get -y update && sudo apt-get -y install lua-check
      - name: Install example site
        run: ln -s ./docs/site-example ./site
      - name: Lint Lua code
        run: make lint-lua

  sh:
    name: Shell
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: sudo apt-get -y update && sudo apt-get -y install shellcheck
      - name: Install example site
        run: ln -s ./docs/site-example ./site
      - name: Lint shell code
        run: make lint-sh
